server:
  port: 8989
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: product_route
          # uri: http://localhost:8084/
          uri: lb://products
          predicates:
            - Path=/product/**
        - id: user_route
          # uri: http://localhost:8083/
          uri: lb://users
          predicates:
            - Path=/feign/**
      discovery:
        locator:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
